// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sfqbhpplirspvgdqlcdl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmcWJocHBsaXJzcHZnZHFsY2RsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMjQxMDcsImV4cCI6MjA3MTkwMDEwN30.muxhvdBm_-1Z89nDIAxvpM2dlZW2dW2At_Q0vdvtZw8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});